import { FastifyPluginCallback } from "fastify";
import { EntityManager } from "typeorm";
import { AllocationRepository } from "../services/AllocationRepository.js";
import { BudgetRepository } from "../services/BudgetRepository.js";
import { TransferRepository } from "../services/TransferRepository.js";
import { DeleteAllocation } from "./DeleteAllocation.js";
import { DeleteTransactions } from "./DeleteTransactions.js";
import { GetAccount } from "./GetAccount.js";
import { GetAccounts } from "./GetAccounts.js";
import { GetAllocation } from "./GetAllocation.js";
import { GetBudget } from "./GetBudget.js";
import { GetBudgets } from "./GetBudgets.js";
import { GetEnvelope } from "./GetEnvelope.js";
import { GetEnvelopeGroup } from "./GetEnvelopeGroup.js";
import { GetEnvelopeGroups } from "./GetEnvelopeGroups.js";
import { GetEnvelopes } from "./GetEnvelopes.js";
import { GetTransaction } from "./GetTransaction.js";
import { GetTransactions } from "./GetTransactions.js";
import { PostAccounts } from "./PostAccounts.js";
import { SaveAllocation } from "./SaveAllocation.js";
import { SaveBudget } from "./SaveBudget.js";
import { SaveEnvelopeGroup } from "./SaveEnvelopeGroup.js";
import { PostTransactions } from "./PostTransactions.js";
import { PostEnvelopes } from "./PostEnvelopes.js";
import { PostTransfers } from "./PostTransfers.js";
import { SignIn } from "./SignIn.js";
import { SignUp } from "./SignUp.js";
import { DeleteEnvelopeGroup } from "./DeleteEnvelopeGroup.js";
import { EditEnvelopeGroup } from "./EditEnvelopeGroup.js";
import { AccountRepository } from "../services/AccountRepository.js";
import { PatchTransactions } from "./PatchTransactions.js";
import { PatchEnvelopes } from "./PatchEnvelopes.js";
import { GetPayees } from "./GetPayees.js";

export const Routes = (deps: {
  JWT_SECRET: string;
  entities: EntityManager;
  allocationRepository: AllocationRepository;
  transferRepository: TransferRepository;
  budgetRepository: BudgetRepository;
  accountRepository: AccountRepository;
}): FastifyPluginCallback => {
  return (server, _, done) => {
    server.register(DeleteAllocation(deps));
    server.register(DeleteEnvelopeGroup(deps));
    server.register(DeleteTransactions(deps));
    server.register(EditEnvelopeGroup(deps));
    server.register(GetAccount(deps));
    server.register(GetAccounts(deps));
    server.register(GetAllocation(deps));
    server.register(GetBudget(deps));
    server.register(GetBudgets(deps));
    server.register(GetEnvelope(deps));
    server.register(GetEnvelopeGroup(deps));
    server.register(GetEnvelopeGroups(deps));
    server.register(GetEnvelopes(deps));
    server.register(GetPayees(deps));
    server.register(GetTransaction(deps));
    server.register(GetTransactions(deps));
    server.register(PatchEnvelopes(deps));
    server.register(PatchTransactions(deps));
    server.register(PostEnvelopes(deps));
    server.register(PostTransactions(deps));
    server.register(PostAccounts(deps));
    server.register(SaveAllocation(deps));
    server.register(SaveBudget(deps));
    server.register(SaveEnvelopeGroup(deps));
    server.register(PostTransfers(deps));
    server.register(SignIn(deps));
    server.register(SignUp(deps));
    done();
  };
};
